import './styles/global.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CCTV 관리자 페이지',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
